// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visits.sql

package visits

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisit = `-- name: CreateVisit :exec
INSERT INTO visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVisitParams struct {
	LinkID    int64       `json:"link_id"`
	Ip        string      `json:"ip"`
	UserAgent string      `json:"user_agent"`
	Referer   pgtype.Text `json:"referer"`
	Status    int32       `json:"status"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) error {
	_, err := q.db.Exec(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	return err
}

const getTotalVisits = `-- name: GetTotalVisits :one
SELECT COUNT(id) AS total_visits FROM visits
`

func (q *Queries) GetTotalVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVisits)
	var total_visits int64
	err := row.Scan(&total_visits)
	return total_visits, err
}

const getVisits = `-- name: GetVisits :many
SELECT
    id,
    link_id,
    created_at,
    ip,
    user_agent,
    status
FROM visits
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type GetVisitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetVisitsRow struct {
	ID        int64              `json:"id"`
	LinkID    int64              `json:"link_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
	Status    int32              `json:"status"`
}

func (q *Queries) GetVisits(ctx context.Context, arg GetVisitsParams) ([]GetVisitsRow, error) {
	rows, err := q.db.Query(ctx, getVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitsRow
	for rows.Next() {
		var i GetVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
