// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package visits

import (
	"context"
)

type Querier interface {
	CreateVisit(ctx context.Context, arg CreateVisitParams) error
	GetTotalVisits(ctx context.Context) (int64, error)
	GetVisits(ctx context.Context, arg GetVisitsParams) ([]GetVisitsRow, error)
}

var _ Querier = (*Queries)(nil)
