// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package postgres_db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links(original_url, short_name, short_url)
VALUES ($1, $2, $3)
RETURNING id, original_url, short_name, short_url
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

type CreateLinkRow struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
	)
	return i, err
}

const deleteLinkByID = `-- name: DeleteLinkByID :execrows
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLinkByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLinkByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
    id,
    original_url,
    short_name,
    short_url
FROM links WHERE id = $1
`

type GetLinkByIDRow struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (GetLinkByIDRow, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i GetLinkByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT
    id,
    original_url,
    short_name,
    short_url
FROM links
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetLinksRow struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) GetLinks(ctx context.Context, arg GetLinksParams) ([]GetLinksRow, error) {
	rows, err := q.db.Query(ctx, getLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksRow
	for rows.Next() {
		var i GetLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalLinks = `-- name: GetTotalLinks :one
    SELECT COUNT(id) AS total_links FROM links
`

func (q *Queries) GetTotalLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalLinks)
	var total_links int64
	err := row.Scan(&total_links)
	return total_links, err
}

const updateLinkByID = `-- name: UpdateLinkByID :one
UPDATE links
SET original_url = $1, short_name = $2, short_url = $3
WHERE id = $4
RETURNING id, original_url, short_name, short_url
`

type UpdateLinkByIDParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
	ID          int64  `json:"id"`
}

type UpdateLinkByIDRow struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) UpdateLinkByID(ctx context.Context, arg UpdateLinkByIDParams) (UpdateLinkByIDRow, error) {
	row := q.db.QueryRow(ctx, updateLinkByID,
		arg.OriginalUrl,
		arg.ShortName,
		arg.ShortUrl,
		arg.ID,
	)
	var i UpdateLinkByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
	)
	return i, err
}
