// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_db

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error)
	DeleteLinkByID(ctx context.Context, id int64) (int64, error)
	GetLinkByID(ctx context.Context, id int64) (GetLinkByIDRow, error)
	GetLinks(ctx context.Context) ([]GetLinksRow, error)
	UpdateLinkByID(ctx context.Context, arg UpdateLinkByIDParams) (UpdateLinkByIDRow, error)
}

var _ Querier = (*Queries)(nil)
