// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortName   string             `json:"short_name"`
	ShortUrl    string             `json:"short_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Visit struct {
	ID        int64              `json:"id"`
	LinkID    int64              `json:"link_id"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
	Referer   pgtype.Text        `json:"referer"`
	Status    int32              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
